### ISSUE TITLE
Random Steam Identifiers being Attached To Other Players

### ISSUE THREAD

**Issue by NeoGaming22** [VORPCORE/VORP-Core#10]
Players are getting other peoples steam ID's, allowing others to play their characters, Also loadouts is randomly attaching wrong Char Indentifiers to other players in Server, Had 3 incidents now where someone lost all thier guns because thier char id was attached to someone completely different in server. And they had thier steam ID attached to another person in server as well, and they were able to play their character.

**Comment by Artzalez** [comment]
Do you know why it could happen?
Example: when creating the character?

**Comment by BulgaRpl** [comment]
It's probably about bugs reported earlier, that's what the author means?

https://github.com/VORPCORE/VORP-WeaponStore/issues/4
https://github.com/VORPCORE/VORP-WeaponStore/issues/5

**Comment by NeoGaming22** [comment]
> Do you know why it could happen?
> Example: when creating the character?

It is happening randomly, it seems to be when a new player creates a character it is attaching wrong steam identifier, Normally id brush it off, but it has happened 3 times now, and very hard to pin point whats causing it
