### ISSUE TITLE
steam autentication cant joint game

### ISSUE THREAD

**Issue by waterpijp** [VORPCORE/VORP-Core#11]
if i use vorp_core i cant join anymore because of some steam issue i use the rockstart version so how do i fix this,,,,,

**Comment by rubi216** [comment]
Can you send a photo of the error, and if you are using the Whitelist, how did you add the steamID to the database?

**Comment by waterpijp** [comment]
i didnt add anything to database do i have to ? and if i turn it of it doasnt work either its just te text error 🚫 You have to have Steam open, please open Steam & restart RedM"

**Comment by rubi216** [comment]
What do you have other than vorp_core? and yes, you should have loaded the sql file from the core

**Comment by waterpijp** [comment]
i didt load the sql but i didnt change anything, i have ghmattimysql, vorp_core, vorp_inputs, vorp_character, vorp_inventory, vorp_metabolism, vorp_stores, vorp_weaponstore, but if i turn of vorp core it works fine

**Comment by rubi216** [comment]
Load the sql files, without a database the scripts wont work, thats why when you disable the core the server works (because you get an empty server)

**Comment by waterpijp** [comment]
i stil get te same error, also when i load the sql it gives me 4 errors. and it also keeps giving errors loading in the other sqls, from the other plugins.

**Comment by rubi216** [comment]
Can you send a photo of the errors, your database and your server.cfg pls?

**Comment by waterpijp** [comment]
![error](https://user-images.githubusercontent.com/54636567/99007808-41b0a980-2545-11eb-8586-af423e6a3c00.PNG)
![cfg](https://user-images.githubusercontent.com/54636567/99007810-42494000-2545-11eb-99a5-04a845708a4f.PNG)
its dutch tough, the sqls from the plugins seemd to load fine now

**Comment by waterpijp** [comment]
![image](https://user-images.githubusercontent.com/54636567/99008111-d74c3900-2545-11eb-90bb-dbcab11df6e5.png)
this is wat i got before

**Comment by waterpijp** [comment]
i got it it was the steam_webapikey i didnt set it, now that i didt it works.
thanks for your time :D

**Comment by rubi216** [comment]
Great! Sorry I didn't respond, I was sleeping xD
