### ISSUE TITLE
I am using vorp core v2, notifications do not work in any way, it used to work

### ISSUE THREAD

**Issue by zeynepfersah** [VORPCORE/VORP-Core#14]
I am using vorp core v2, notifications do not work in any way, it used to work

**Comment by Artzalez** [comment]
can you show me an example of the code ?

**Comment by trublud** [comment]
TriggerEvent("vorp:Tip", 'A Zombie! what?!', 3000)	

will produce 
![image](https://user-images.githubusercontent.com/5308859/104108022-69d73300-527e-11eb-8680-4f81d3483ad8.png)

**Comment by desperadisse** [comment]
Same issue with same error message

**Comment by trublud** [comment]
In the mean time in installed redemrp_notification and edited Notifications.js of vorp_core as a private workaround

 emit('redemrp_notification:start', text, 2, "warning");
    
  //  Citizen.invokeNative("0xB2920B9760F0F36B", struct1, struct2, 1);

**Comment by desperadisse** [comment]
> 
> 
> In the mean time in installed redemrp_notification and edited Notifications.js of vorp_core as a private workaround
> 
> emit('redemrp_notification:start', text, 2, "warning");
> 
> // Citizen.invokeNative("0xB2920B9760F0F36B", struct1, struct2, 1);

It work :)
Thx
