### ISSUE TITLE
List all the project that NEEDS to be translated to lua

### ISSUE THREAD

**Issue by Abelfy** [VORPCORE/VORP-Core#16]

**Comment by Thodde26** [comment]
All vorp scripts ;)

**Comment by outsider31000** [comment]
> All vorp scripts ;)

they will stay C# so that we don't see loads of different cores out there. and then have channels being flooded with support.

**Comment by Local9** [comment]
To make it clear; my current goal is to bring Character and Inventory inside Core.

**Comment by Local9** [comment]
Closing this as there is an active lua project
