### ISSUE TITLE
[URGENT] SERVER ERROR ON STARTUP

### ISSUE THREAD

**Issue by lyoneofficial** [VORPCORE/VORP-Core#22]
Hi,
When i start my server it loads but when finish it crash with this error
![redm server error](https://user-images.githubusercontent.com/87578373/157293699-36d9327c-bb1c-4290-824e-a280de1f0cb2.png)

**Comment by Local9** [comment]
Make sure you have the correct depenancies.
https://github.com/VORPCORE/VORP-Core#readme
