### ISSUE TITLE
Changing the config causes errors 

### ISSUE THREAD

**Issue by Nathanking21** [VORPCORE/VORP-Core#24]
for some reason when trying to edit things like respawn time or starting cash it causes multiple errors in multiple scripts for some reason you cant even change one letter or number without the whole thing causing errors and have no idea why changing things in the config causes problems and would like any advice for fixing this thank you.

**Comment by Local9** [comment]
Currently recommend trying to use the Lua project https://github.com/VORPCORE/vorp-core-lua as this one is currently under a major refactor.

**Comment by Nathanking21** [comment]
@Local9 yes ive tried to use this one but the hunting script does not load correctly and gets an error and u cannot change ur character and when you do u stay at the selection screen while the textures turn very bad https://github.com/VORPCORE/vorp-core-lua

**Comment by Local9** [comment]
If you can provide the error message, it'll help narrow down where its throwing out. The current implementation of config reading in the project is not the best, but I can look into it and see if something can be done.

**Comment by Nathanking21** [comment]
@Local9 it is fixed now apparently using notepad instead visual studio causes errors

**Comment by Local9** [comment]
Ah, you had a BOM encoding error, yea Visual Studio does that annoyingly, using Visual Studio Code is better imho.
