### ISSUE TITLE
Steam Authentication Error

### ISSUE THREAD

**Issue by JoelJoos** [VORPCORE/VORP-Core#31]
I recently set up a VORP RedM server. The Server runs just fine, however when I want to connect to it using RedM, I get the error "...you have to have Steam open..." & "... you are running Steam and it is signed in. ...". However, as the message suggests I have steam opened. Is it possible that there is a problem because I didn't buy the game on steam?

**Comment by outsider31000** [comment]
this is not the script to be used. look for premade vorp server
