### ISSUE TITLE
Dead Camera Problem

### ISSUE THREAD

**Issue by BulgaRpl** [VORPCORE/VORP-Core#7]
The camera always follows the last person who carried us.
Even if that person leaves us somewhere, the camera will follow him.

**Comment by DoaherisTR** [comment]
> The camera always follows the last person who carried us.
> Even if that person leaves us somewhere, the camera will follow him.

Did you find the solution?

**Comment by Demo4889** [comment]
This has been fixed in the new version I am working on.
