### ISSUE TITLE
Fatal Errors When Whitelist is OFF

### ISSUE THREAD

**Issue by BulgaRpl** [VORPCORE/VORP-Core#8]
![image](https://user-images.githubusercontent.com/69915160/96561253-9acb4b80-12bf-11eb-849e-eec8db5b8cba.png)

**Comment by Artzalez** [comment]
Try this version you can replace server dll
[vorp_core.zip](https://github.com/VORPCORE/VORP-Core/files/5523171/vorp_core.zip)

**Comment by BulgaRpl** [comment]
I will upload it today on my server and let you know. 
Can you show what exactly was changed or upload the source code?

**Comment by Artzalez** [comment]
Changed LoadUser Function

**Comment by BulgaRpl** [comment]
At the moment I have no errors, but I also have less activity on the server. Maybe this solution works.

**Comment by Artzalez** [comment]
On releases, thanks for the report, @BulgaRpl
